kyverno/website

content/en/docs/Writing policies/_index.md, content/en/docs/Writing policies/autogen.md, content/en/docs/Writing policies/background.md, content/en/docs/Writing policies/generate.md, content/en/docs/Writing policies/match-exclude.md, content/en/docs/Writing policies/mutate.md, content/en/docs/Writing policies/preconditions.md, content/en/docs/Writing policies/structure.md, content/en/docs/Writing policies/validate.md, content/en/docs/Writing policies/variables.md
Fixes https://github.com/kyverno/website/issues/13
=> document ordering and (lack of) override behaviors

content/en/docs/Writing policies/variables.md
=> add note on escaping "-" for JMESPATH processing

content/en/docs/Installation/_index.md, content/en/docs/Introduction/_index.md, content/en/docs/Writing policies/autogen.md, content/en/docs/Writing policies/background.md, content/en/docs/Writing policies/validate.md, content/en/docs/Writing policies/variables.md
Use `{{% alert %}}` [shortcodes](https://www.docsy.dev/docs/adding-content/shortcodes/) from Docsy to get styled callouts for notes and warnings.
=> Use Docsy callouts for notes

README.md
[Rendered](https://github.com/sftim/kyverno-website/blob/20201127_tweak_readme/README.md#readme).
=> Add README details about local previewing

content/en/docs/Community/_index.md
=> Tidy meeting notes hyperlink

render/render.go
=> fix misspelling

content/en/docs/Installation/_index.md, content/en/docs/Introduction/_index.md, content/en/docs/Writing policies/background.md, content/en/docs/Writing policies/generate.md, content/en/docs/Writing policies/match-exclude.md, content/en/docs/Writing policies/mutate.md, content/en/docs/Writing policies/validate.md, content/en/docs/Writing policies/variables.md, content/en/policies/_index.md
`dev` branch was deleted. Created temp `updates` branch instead.
This PR is for minor clean-up (grammar, consistency, formatting, etc.) and introduces no new content.
=> minor clean-up

content/en/policies/pod-security/default/_index.md, content/en/policies/pod-security/restricted/_index.md
=> add kustomize links and details

content/en/docs/Installation/_index.md, content/en/docs/Writing policies/variables.md
Adding Kyverno compatibility matrix (closes https://github.com/kyverno/website/issues/66) and nested JMESPath expressions (addresses https://github.com/kyverno/website/projects/1#card-52841871).
=> Add compat matrix; add JMESPath nesting

layouts/partials/footer.html
=> update Nirmata URL

content/en/docs/Writing policies/autogen.md, content/en/docs/Writing policies/background.md, content/en/docs/Writing policies/external-data-sources.md, content/en/docs/Writing policies/preconditions.md, content/en/docs/Writing policies/tips.md, content/en/docs/Writing policies/variables.md
Fixes: #81
I separated variables from external data lookups, as both sections are fairly long.
=> docs for APICall 

content/en/docs/Writing policies/match-exclude.md
Signed-off-by: NoSkillGirl <singhpooja240393@gmail.com>
closes - https://github.com/kyverno/website/issues/82
=> added namespace selector example

content/en/docs/Kyverno CLI/_index.md
previous PR - https://github.com/kyverno/website/pull/15
=> Document - policy report

content/en/docs/Writing policies/preconditions.md
Signed-off-by: Arsh Sharma <arshsharma461@gmail.com>
Fixes #94
=> docs(preconditions): documented set operations for In and NotIn

content/en/docs/Writing policies/match-exclude.md
..to list of match / exclude elements
=> add namespaceSelector

content/en/resources/_index.md
=> add new blog

content/en/resources/_index.md
=> Add Cloud Native Islamabad webinar

content/en/docs/Kyverno CLI/_index.md
Signed-off-by: NoSkillGirl <singhpooja240393@gmail.com>
closes https://github.com/kyverno/website/issues/105
=> Updated doc for namespace selector in Kyverno CLI

content/en/docs/Kyverno CLI/_index.md
closes https://github.com/kyverno/website/issues/92
=> Doc: Test Command

content/en/docs/Writing policies/variables.md
Closes https://github.com/kyverno/website/issues/115.
=> Add variables for image properties

content/en/docs/Installation/_index.md
Closes https://github.com/kyverno/website/issues/66.
=> Update compatibility matrix

content/en/resources/_index.md
=> Add policy reporter episode

content/en/docs/Installation/_index.md, content/en/docs/Writing policies/match-exclude.md
closes https://github.com/kyverno/website/issues/125
closes https://github.com/kyverno/website/issues/107
=> Doc: Remove permission And match and exclude resource

content/en/resources/_index.md
=> update start timestamp

content/en/Community/_index.md
=> add contributors meeting

content/en/docs/Writing policies/variables.md
=> update image variable info

content/en/docs/Writing policies/background.md
=> Update background scan behavior

content/en/docs/Installation/_index.md, content/en/docs/Kyverno CLI/_index.md, content/en/docs/Writing policies/external-data-sources.md, content/en/docs/Writing policies/mutate.md
Closes https://github.com/kyverno/website/issues/108
=> Doc updates

content/en/policies/other/add_labels.md, content/en/policies/other/exclude_namespaces_dynamically.md, content/en/policies/other/require_image_checksum.md
Missed adding the new files in the last PR! 
=> add new policies

content/en/docs/Writing policies/variables.md
=> update images sample

content/en/policies/other/disallow_localhost_services.md
=> render new policy

layouts/index.json
=> fix filters

content/en/pod-security.md
=> inline policy list

content/en/docs/CRDs/_index.md
I have made both changes on issue #173.
=> updated Resource Definitions #173

Makefile
Signed-off-by: Yashvardhan Kukreja <yash.kukreja.98@gmail.com>
closes #171
=> fix: npm dependency bootstrap and hugo builds and executions

content/en/docs/Kyverno CLI/_index.md, content/en/docs/Writing policies/external-data-sources.md, content/en/docs/Writing policies/generate.md, content/en/docs/Writing policies/mutate.md, content/en/docs/Writing policies/validate.md, content/en/docs/Writing policies/variables.md
closes #127 
closes #134 
closes #124 
closes #149 
closes #155 
closes #165 
closes #169
=> updates for 1.3.6

content/en/policies/other/allowed_pod_priorities.md, content/en/policies/other/limit_containers_per_pod.md, content/en/policies/other/require_imagepullsecrets.md
Renders the three new policies
=> render new policies

config/_default/params.toml, content/en/Community/_index.md, content/en/_index.html
=> update slack links and help

assets/scss/main.scss, package-lock.json
=> fix anchor spacing with fixed header

content/en/docs/Writing policies/background.md
current link goes to https://kyverno.io/docs/writing-policies/background/content/en/docs/Installation/_index.md/#flags , resulting in a 404
=> fix broken link

content/en/docs/Writing policies/preconditions.md
=> add missing operators

content/en/docs/Monitoring Kyverno With Prometheus Metrics/_index.md, content/en/docs/Monitoring Kyverno With Prometheus Metrics/bonus-grafana-dashboard.md, content/en/docs/Monitoring Kyverno With Prometheus Metrics/policy-changes-info.md, content/en/docs/Monitoring Kyverno With Prometheus Metrics/policy-rule-execution-latency.md, content/en/docs/Monitoring Kyverno With Prometheus Metrics/policy-rule-info-total.md, content/en/docs/Monitoring Kyverno With Prometheus Metrics/policy-rule-results-info.md
=> update metric docs

content/en/docs/Installation/_index.md
Signed-off-by: Velkov <valentin.velkov@sap.com>
=> Add 'generateSuccessEvents' flag

content/en/docs/Installation/_index.md
Signed-off-by: vineethvanga18 <reddy.8@iitj.ac.in>
Add version 1.4 to compatibility matrix in docs
=> Add kyverno 1.4 to matrix

content/en/docs/Kyverno CLI/_index.md, content/en/docs/Writing policies/match-exclude.md
Signed-off-by: viveksahu26 <vivekkumarsahu650@gmail.com>
=> Updated the documentation of the Test section of Kyverno CLI

content/en/docs/Policy Reports/_index.md
- clarify that Policy Report is for current resources
- add link to policy reporter
=> clarify use of policy report and add link to Policy Reporter

content/en/docs/Writing policies/match-exclude.md
Signed-off-by: RinkiyaKeDad <arshsharma461@gmail.com>
=> updating docs to reflect deprecation of resources.name

content/en/docs/Installation/_index.md
=> fix note about replicas

content/en/docs/Kyverno CLI/_index.md
closes https://github.com/kyverno/website/issues/205
=> fix ResourceName for test command

content/en/policies/best-practices/check_deprecated_apis.md
=> render policy sample check_deprecated_apis

content/en/docs/Writing policies/preconditions.md
See https://github.com/kyverno/kyverno/issues/2165 for reference.
=> add note about wildcard support on conditions

content/en/docs/Writing policies/match-exclude.md
Signed-off-by: RinkiyaKeDad <arshsharma461@gmail.com>
=> fix clusterRoles casing and usage in selecting resources page

content/en/docs/Policy Reports/_index.md
Signed-off-by: Frank Jogeleit <fj@move-elevator.de>
Update Policy Reporter Repository after transfer
=> Update Policy Reporter Repository

layouts/robots.txt
=> Allow crawlers to resume indexing pages

config/_default/config.toml, config/_default/menus/menu.en.toml, config/_default/params.toml, content/en/Community/_index.md, content/en/_index.html
Fixes https://github.com/kyverno/website/issues/64.
Added release versions and moved GitHub to footer. Also added line breaks to fix "About Kyverno" rendering.
=> add releases

config/_default/config.toml
=> fix 1.4.1 version

README.md, config/_default/config.toml
=> add release versioning instructions

content/en/docs/Writing policies/match-exclude.md
Signed-off-by: RinkiyaKeDad <arshsharma461@gmail.com>
=> updating documentation to reflect any and all tags 

content/en/docs/Writing policies/preconditions.md, content/en/policies/other/annotation_lifetime.md
Signed-off-by: Trey Dockendorf <tdockendorf@osc.edu>
Document https://github.com/kyverno/kyverno/pull/2214
=> Document duration operators

content/en/docs/Installation/_index.md, content/en/docs/Policy Reports/_index.md, content/en/docs/Writing policies/match-exclude.md, content/en/policies/best-practices/check_deprecated_apis.md, content/en/policies/best-practices/disallow_cri_sock_mount/disallow_cri_sock_mount.md, content/en/policies/best-practices/disallow_default_namespace/disallow_default_namespace.md, content/en/policies/best-practices/require_pod_requests_limits/require_pod_requests_limits.md, content/en/policies/cert-manager/limit-dnsnames.md, content/en/policies/other/add-imagepullsecrets.md, content/en/policies/other/add_nodeSelector.md, content/en/policies/other/block-pod-exec-by-namespace-label.md, content/en/policies/other/block-pod-exec-by-namespace.md, content/en/policies/other/block-pod-exec-by-pod-and-container.md, content/en/policies/other/block-pod-exec-by-pod-label.md, content/en/policies/other/block-pod-exec-by-pod-name.md, content/en/policies/other/pod_lifetime_annotation/enforce_pod_duration.md, content/en/policies/other/restrict_usergroup_fsgroup_id.md, content/en/policies/other/spread_pods_across_topology.md, content/en/policies/other/verify_image.md
Closes #242 
Closes #234 
Closes #179 
Closes #248
=> [1.4.1] fixes, updates; policy rendering

README.md, content/en/docs/Installation/_index.md, content/en/docs/Policy Reports/_index.md, content/en/policies/best-practices/check_deprecated_apis.md, content/en/policies/best-practices/disallow_cri_sock_mount/disallow_cri_sock_mount.md, content/en/policies/best-practices/disallow_default_namespace/disallow_default_namespace.md, content/en/policies/best-practices/require_pod_requests_limits/require_pod_requests_limits.md, content/en/policies/cert-manager/limit-dnsnames.md, content/en/policies/other/add-imagepullsecrets.md, content/en/policies/other/add_nodeSelector.md, content/en/policies/other/block-pod-exec-by-namespace-label.md, content/en/policies/other/block-pod-exec-by-namespace.md, content/en/policies/other/block-pod-exec-by-pod-and-container.md, content/en/policies/other/block-pod-exec-by-pod-label.md, content/en/policies/other/block-pod-exec-by-pod-name.md, content/en/policies/other/pod_lifetime_annotation/enforce_pod_duration.md, content/en/policies/other/restrict_usergroup_fsgroup_id.md, content/en/policies/other/spread_pods_across_topology.md, render/README.md
Also addresses #234 , #179 , #248
Renders latest policies
=> [main] README updates; remove reference to Kyverno CM; render policies

content/en/docs/Monitoring Kyverno With Prometheus Metrics/admission-requests.md, content/en/docs/Monitoring Kyverno With Prometheus Metrics/admission-review-latency.md, content/en/docs/Monitoring Kyverno With Prometheus Metrics/policy-changes.md, content/en/docs/Monitoring Kyverno With Prometheus Metrics/policy-execution-latency.md, content/en/docs/Monitoring Kyverno With Prometheus Metrics/policy-results-info.md
Signed-off-by: Yashvardhan Kukreja <yash.kukreja.98@gmail.com>
closes #239 
Updates the metric-related docs to comply with the recent metric re-design in Kyverno.
Refer: https://github.com/kyverno/kyverno/pull/2157
=> updated: metrics-related docs with respect to new metric updates

config/_default/config.toml
=> 1.4.1 -> https://release-1-4-1.kyverno.io/

content/en/_index.html
Fixes #256 
- Implements Bootstrap's [img-fluid](https://getbootstrap.com/docs/4.0/content/images/#responsive-images) class
**Some screenshots from different devices:**
Device | Before | After 
:-------------------------:|:-------------------------:|:-------------------------:
Desktop | ![old desktop](https://user-images.githubusercontent.com/55556994/129528206-fd0c782a-38ff-4123-acf3-d5246a9076c1.png) |  <img src="https://user-images.githubusercontent.com/55556994/129527695-5fcf3529-b8b2-4b38-9c7e-e8e534c4590d.png">
iPad | <img src="https://user-images.githubusercontent.com/55556994/129529303-4f2b89da-e974-4496-9d21-697cad74a3f6.png" height=300> | <img src="https://user-images.githubusercontent.com/55556994/129527701-a7702101-3d6b-4364-84bb-cdd78ddf6fd3.png" height=300> 
iPhone X | <img …
=> Fix: Responsive CNCF logo

content/en/docs/Installation/_index.md
related PR - https://github.com/kyverno/kyverno/pull/2263
=> Removing Cleanup Webhook Configurations from the website doc

content/en/resources/_index.md
Added [this](https://medium.com/@shubhampalriwala/understanding-kyverno-policies-7e2d8651d7b1) blog to the Resources section as suggested by Chip on Slack:
=> Added new Blog

assets/js/policy.js, assets/scss/custom.scss, content/en/policies/_index.md, layouts/partials/back-button.html, layouts/partials/footer.html, layouts/partials/icon-sprites.html, layouts/partials/policies/toggle.html, layouts/policies/list.html, layouts/policies/single.html
@chipzoller , @JimBugwadia, I made a few improvements based on some cards that Chip created.
1. [Add note to the top of the policies page](https://github.com/kyverno/website/projects/3#column-15055985)
2. [extend code blocks' width](https://github.com/kyverno/website/projects/3#card-64762200)
3. [Improve filter on mobile](https://github.com/kyverno/website/projects/3#card-64582384)
4. [Add a back to `all policies` button](https://github.com/kyverno/website/projects/3#card-64762195)
5. [Remove url query from policy single pages](https://github.com/kyverno/website/projects/3#card-64762205)
=> Policies page enhancements

.github/ISSUE_TEMPLATE/documentation.md, .github/PULL_REQUEST_TEMP.md
=> created an issue template

content/en/resources/_index.md
Signed-off-by: Anita-ihuman <charlesanita403@gmail.com>
This PR is used to upload a new blog post on Kyverno
=> uploaded new blogpost

content/en/docs/Kyverno CLI/_index.md
Signed-off-by: NoSkillGirl <singhpooja240393@gmail.com>
=> correcting policy name in variable file | CLI

content/en/docs/Writing policies/verify-images.md
Fixes https://github.com/kyverno/website/issues/292, https://github.com/kyverno/website/issues/318
=> docs for attestations

config/_default/config.toml
=> add v1.4.3

content/en/docs/Kyverno CLI/_index.md
Closes #298 
cc - @NoSkillGirl
=> [1.5.0] Adding documentation for CLI Global Variables

content/en/docs/CRDs/_index.md, content/en/docs/Installation/_index.md, content/en/docs/Monitoring Kyverno With Prometheus Metrics/policy-rule-info-total.md, content/en/docs/Writing policies/tips.md, content/en/docs/Writing policies/webhooks.md
Signed-off-by: ShutingZhao <shutting06@gmail.com>
Closes #314.
Closes https://github.com/kyverno/kyverno/issues/1983.
=> [1.5.0] Update docs for dynamic webhooks

content/en/docs/Writing policies/mutate.md, content/en/docs/Writing policies/validate.md
=> update foreach docs for lists

config/_default/config.toml
=> add v1.5.0

Dockerfile, Makefile
This PR fixes the build of the website locally using containers.
So far it should work, however I still have to test building from a clean checkout (will do that tomorrow).
Feel free to suggest anything, review and/or merge if you think it's ready.
=> Fix website build using containers

content/en/docs/Writing policies/mutate.md, content/en/policies/best-practices/nginx-custom-snippets/disallow-custom-snippets.md, content/en/policies/best-practices/require_drop_all/require_drop_all.md, content/en/policies/best-practices/require_drop_cap_net_raw/require_drop_cap_net_raw.md, content/en/policies/other/add_env_vars_from_cm/add-env-vars-from-cm.md, content/en/policies/other/prepend_image_registry/prepend_image_registry.md, content/en/policies/other/restrict_secrets_by_name/restrict-secrets-by-name.md, content/en/policies/pod-security/restricted/restrict-seccomp/restrict-seccomp.md
=> update mutate foreach example; minor linting; render policies

content/en/docs/Writing policies/mutate.md, content/en/policies/best-practices/nginx-custom-snippets/disallow-custom-snippets.md, content/en/policies/best-practices/require_drop_all/require_drop_all.md, content/en/policies/best-practices/require_drop_cap_net_raw/require_drop_cap_net_raw.md, content/en/policies/other/add_env_vars_from_cm/add-env-vars-from-cm.md, content/en/policies/other/prepend_image_registry/prepend_image_registry.md, content/en/policies/other/restrict_secrets_by_name/restrict-secrets-by-name.md
=> Updates for release-1-5-0

content/en/docs/Kyverno CLI/_index.md
Signed-off-by: NoSkillGirl <singhpooja240393@gmail.com>
Related issue - https://github.com/kyverno/website/issues/281
=> [1.5.0] Updated CLI doc for `apply` command result

content/en/docs/Writing policies/preconditions.md
Fixes: #349
Add details and example for comparing resource quantities.
=> [1.5.2] Added docs for resource quantity comparison

content/en/docs/Installation/_index.md, content/en/docs/Monitoring Kyverno With Prometheus Metrics/_index.md, content/en/docs/Writing policies/variables.md, content/en/resources/_index.md
=> [1.5.2] extend escaping vars

.gitignore, content/en/docs/Releases/_index.md, content/en/docs/Writing policies/mutate.md, content/en/policies/cert-manager/limit-duration/limit-duration.md, content/en/policies/other/add_node_affinity/add_node_affinity.md, content/en/policies/other/allowed_pod_priorities/allowed_pod_priorities.md, content/en/policies/other/disable_automountserviceaccounttoken/disable-automountserviceaccounttoken.md, content/en/policies/other/disallow_all_secrets/disallow_all_secrets.md, content/en/policies/other/exclude_namespaces_dynamically.md, content/en/policies/other/pod_lifetime_annotation/enforce_pod_duration.md, content/en/policies/other/prepend_image_registry/prepend_image_registry.md, content/en/policies/other/protect_node_taints/protect-node-taints.md, content/en/policies/other/require_unique_external_dns/require_unique_external_dns.md, content/en/policies/other/require_unique_uid_per_workload/require_unique_uid_per_workload.md, content/en/policies/traefik/disallow_default_tlsoptions/disallow_default_tlsoptions.md
Includes updates, fixes for Kyverno v1.5.2 and rendering of all latest policies.
=> Updates for v1.5.2

content/en/Community/_index.md
=> minor corrections and edits

content/en/policies/best-practices/add_safe_to_evict.md, content/en/policies/other/add-imagepullsecrets-for-containers-and-initcontainers.md, content/en/policies/other/add_certificates_volume/add_certificates_volume.md, content/en/policies/other/check_serviceaccount/check_serviceaccount.md, content/en/policies/other/inject_sidecar_deployment/inject_sidecar_deployment.md, content/en/policies/other/mitigate_log4shell/mitigate_log4shell.md, content/en/policies/other/prepend_image_registry/prepend_image_registry.md, content/en/policies/other/restrict_automount_sa_token/restrict_automount_sa_token.md, content/en/policies/other/restrict_service_account.md
=> render policies

content/en/docs/Writing policies/match-exclude.md
closes https://github.com/kyverno/website/issues/424
=> Doc update to wildcard support match label selector

layouts/partials/navbar.html
=> reduce text to prevent wrap on small/mobile screens

content/en/docs/security/_index.md
=> fix typo and clarify webhook mutual auth

content/en/docs/Writing policies/verify-images.md
signed-off by [Oshi Gupta](https://github.com/oshi36)  email - oshiagupta36@gmail.com
Fixes #452
Fixed auto-gen URL link in verify-images under writing-policies
=> fixed auto-gen URL

content/en/docs/Writing policies/variables.md
=> document custom JMESPath truncate function

content/en/docs/Kyverno CLI/_index.md
Signed-off-by: Abhinav Sinha <zeborg3@gmail.com>
Closes #417
=> [1.6.0] Updated docs for `kyverno test` command with git path

content/en/docs/Writing policies/variables.md
Documentation for https://github.com/kyverno/kyverno/pull/2717.
=> [1.6.0] Document `pattern_match` JMESPath custom function

content/en/docs/Writing policies/validate.md
Accompanying PR to this https://github.com/kyverno/kyverno/pull/2622.
=> [1.6.0] *Range operators

content/en/docs/Writing policies/preconditions.md
Signed-off-by: anushkamittal20 <anumittal4641@gmail.com>
Added documentation for new operators for [this](https://github.com/kyverno/kyverno/pull/2543)
=> [1.6.0] Added doc for new operators

content/en/docs/Writing policies/variables.md
Closes #392 
Signed-off-by: Kumar Mallikarjuna <kumarmallikarjuna1@gmail.com>
=> Update JMESPath arithmetic functions' docs

content/en/docs/Writing policies/validate.md
Closes #410 
Signed-off-by: Kumar Mallikarjuna <kumarmallikarjuna1@gmail.com>
=> Namespace Specific ValidationFailureAction

config/_default/config.toml
=> add 1.6.0 release to menu in main

README.md, content/en/docs/Kyverno CLI/_index.md, content/en/docs/Writing policies/external-data-sources.md, content/en/docs/Writing policies/jmespath.md
Minor doc updates, mostly JMESPath section updates. If accepting and merging, please squash so it's easier to cherry pick later.
=> Minor doc updates

README.md, content/en/docs/Writing policies/jmespath.md
Cherry-picks #469 
We should remember to squash and merge this one.
=> Cherry-pick updates to 1.6 branch

content/en/docs/Kyverno CLI/_index.md, content/en/docs/Writing policies/external-data-sources.md, content/en/docs/Writing policies/jmespath.md
Missed cherry picking a commit based on an earlier PR.
=> Pick up missing commits

content/en/docs/Writing policies/jmespath.md, content/en/policies/best-practices/add_safe_to_evict/add_safe_to_evict.md, content/en/policies/other/allowed_label_changes/allowed-label-changes.md, content/en/policies/other/require_imagepullsecrets/require_imagepullsecrets.md
* Adds a new policy called "Allowed Label Changes"
* Updates JMESPath docs page
Needs to be cherry picked to release-1-6-0
=> JMESPath doc updates; render policies

content/en/docs/Writing policies/jmespath.md, content/en/policies/best-practices/add_safe_to_evict/add_safe_to_evict.md, content/en/policies/other/allowed_label_changes/allowed-label-changes.md, content/en/policies/other/require_imagepullsecrets/require_imagepullsecrets.md
Cherry picks PR #472 to release 1.6.0
=> [1.6.0] Cherry pick

content/en/docs/Writing policies/external-data-sources.md
Signed-off-by: Sambhav Kothari <sambhavs.email@gmail.com>
Adds better docs for the image registry call.
=> Add documentation on the fields returned by the `imageRegistry` call

content/en/policies/best-practices/disallow-empty-ingress-host/disallow_empty_ingress_host.md, content/en/policies/best-practices/disallow_default_namespace/disallow_default_namespace.md, content/en/policies/best-practices/require_drop_all/require_drop_all.md, content/en/policies/best-practices/require_drop_cap_net_raw/require_drop_cap_net_raw.md, content/en/policies/best-practices/require_pod_requests_limits/require_pod_requests_limits.md, content/en/policies/cert-manager/limit-dnsnames/limit-dnsnames.md, content/en/policies/openshift/disallow-deprecated-apis/disallow-deprecated-apis.md, content/en/policies/openshift/disallow-jenkins-pipeline-strategy/disallow-jenkins-pipeline-strategy.md, content/en/policies/openshift/disallow-security-context-constraint-anyuid/disallow-security-context-constraint-anyuid.md, content/en/policies/openshift/disallow-self-provisioner-binding/disallow-self-provisioner-binding.md, content/en/policies/openshift/enforce-etcd-encryption/enforce-etcd-encryption.md, content/en/policies/openshift/validate-routes/check-routes.md, content/en/policies/other/block_images_with_volumes/block-images-with-volumes.md, content/en/policies/other/block_stale_images/block-stale-images.md, content/en/policies/other/exclude_namespaces_dynamically.md, content/en/policies/other/limit-configmap-for-sa/limit_configmap_for_sa.md, content/en/policies/other/limit-hostpath-type-pv/limit_hostpath_type_pv.md, content/en/policies/other/mutate-large-termination-gps.md, content/en/policies/other/prevent-cr8escape/prevent-cr8escape.md, content/en/policies/other/restrict_node_label_changes.md, content/en/policies/other/restrict_node_label_creation.md
Renders all policies in kyverno/policies rather than cherry picking missed commits in the past.
=> [1.6.0] render all policies

.github/ISSUE_TEMPLATE/enhancement.yml, content/en/docs/Kyverno CLI/_index.md, content/en/docs/Troubleshooting/_index.md, content/en/docs/Writing policies/match-exclude.md
Fixes #479 
Closes #485 
Closes #489 
* Adds a new "enhancement" issue template to documentation issues.
* Adds a missing `globalValues` section to the variables file in the CLI `test` command.
* Clarifies that variables can be used to test context variables like those in API calls.
* Adds a new troubleshooting step for EKS users regarding VPC CNI version.
* Fixes indentation on match/exclude page.
=> add enhancement issue template; fixes and additions

content/en/docs/Writing policies/match-exclude.md
closes https://github.com/kyverno/website/issues/494
=> Wildcard update

content/en/resources/_index.md
Signed-off-by: ShutingZhao <shuting@nirmata.com>
=> Add new slides for Kyverno workshop

content/en/docs/Writing policies/jmespath.md, content/en/docs/Writing policies/variables.md
Cherry picks the JMESPath doc updates to 1.6 release branch.
=> [1.6] Cherry pick JMESPath updates (#504)

content/en/docs/Kyverno CLI/_index.md
closes https://github.com/kyverno/website/issues/499
Related PR ; https://github.com/kyverno/kyverno/pull/3488
=> removing validate cmd

content/en/docs/Writing policies/mutate.md
Signed-off-by: ShutingZhao <shuting@nirmata.com>
Closes https://github.com/kyverno/website/issues/520.
=> Add mutate existing docs for 1.7.0

content/en/docs/Writing policies/generate.md
Signed-off-by: prateekpandey14 <prateekpandey14@gmail.com>
Closes #536
Add docs for generate policies on existing resources
=> Add docs for generate policies on existing resources

content/en/docs/Installation/_index.md
Closes https://github.com/kyverno/website/issues/537.
N/A
=> Add webhookTimeout

content/en/docs/Kyverno CLI/_index.md
Signed-off-by: Tathagata Paul <tathagatapaul7@gmail.com>
Closes #505
=> add docs for support for roles, cluster roles and subjects in CLI

content/en/docs/Installation/_index.md, content/en/docs/Kyverno CLI/_index.md, content/en/docs/Writing policies/autogen.md, content/en/docs/Writing policies/external-data-sources.md, content/en/docs/Writing policies/generate.md, content/en/docs/Writing policies/jmespath.md, content/en/docs/Writing policies/match-exclude.md, content/en/docs/Writing policies/variables.md, content/en/docs/Writing policies/verify-images.md, content/en/policies/kasten/k10-data-protection-by-label/k10-check-data-protection-by-label.md, content/en/policies/other/generate_networkpolicy_existing/generate-networkpolicy-existing.md
Closes #544
Closes #535 
Closes #533 
Closes #532 
Closes #528 
Closes #527 
Closes #519 
Closes #502 
Closes #501 
* Adds most of the issues addressed in 1.7.0. Will be updated later as time allows.
* Manually copies-and-pastes the content from https://github.com/kyverno/website/commit/733be7cd6bce6a62eeb01a6197b0460d9e872138 to present in `main`
=> 1.7.0 doc updates

config/_default/config.toml
* Adds version drop-down to site
=> Adds release version

config/_default/config.toml
* (hopefully) fixes the redirect from main back to the latest release
=> fix returning to latest release from main

config/_default/config.toml, content/en/resources/_index.md
* Adds a blog post from Nirmata on the Kyverno 1.7.0 release
=> Add Nirmata blog on Kyverno v1.7.0 release

content/en/docs/Kyverno CLI/_index.md, content/en/docs/Writing policies/jmespath.md
Closes #486 
Closes #481 
* Adds cross-link to the other filter
* Rewrite of the `test` CLI docs
Needs cherry pick to 1.7.0
=> [1.7.0] Add cross-link, re-write test docs

content/en/docs/Writing policies/verify-images.md
=> fix example policies

content/en/docs/High Availability/_index.md, content/en/docs/Installation/_index.md, content/en/docs/Troubleshooting/_index.md
* Updates docs in various places to acknowledge the default exclusion of the Kyverno Namespace in the Helm chart v2.5.0
=> updates for Helm 2.5.0 and Kyverno Namespace exclusion

content/en/policies/kasten/k10-data-protection-by-label/k10-check-data-protection-by-label.md, content/en/policies/kasten/k10-minimum-retention/k10-override-minimum-retentions.md, content/en/policies/openshift/unique-routes/unique-routes.md, content/en/policies/other/require-base-image/require-base-image.md, content/en/policies/velero/validate-cron-schedule/validate-cron-schedule.md, render/go.mod, render/render.go, render/root.go
Fixes https://github.com/kyverno/website/issues/59
Update render
=> 59 fix render

content/en/docs/Releases/_index.md
n/a
add cherry-pick details and other notes on managing issues and releases
=> add cherry pick and release planning details

content/en/Community/_index.md
Fixed the timelines for the community and contributor
meetings
Signed-off-by: Abhisman Sarkar <abhisman.sarkar@gmail.com>
Fixes #576  @realshuting 
Fixes the timelines for the Community and Contributor meetings
=> Updated content/en/Community/_index.md

content/en/policies/psa/add-psa-labels/add-psa-labels.md, content/en/policies/psa/deny-privileged-profile/deny-privileged-profile.md
* Cherry picks #581  to release1.7
=> Cherry pick 2 PSA policies to release-1.7

content/en/docs/Kyverno CLI/_index.md
=> fix: Update _index.md

content/en/docs/Writing policies/verify-images.md
Signed-off-by: Dan Garfield <dan@codefresh.io>
"fail" is case sensitive. Applying the example manifest will fail. 
Signed-off-by: Dan Garfield <dan@codefresh.io>
=> Fix check-image cluster policy

content/en/resources/_index.md
Signed-off-by: Anais Urlichs <33576047+AnaisUrlichs@users.noreply.github.com>
=> adding YT tutorials from the Aqua Open Source Channel

content/en/docs/Writing policies/verify-images.md
Remove an extraneous quote.
Signed-off-by: Abhilash Raj <maxking@asynchronous.in>
=> docs: Fix the YAML example for keyless signature.

content/en/docs/Kyverno CLI/_index.md
Signed-off-by: Gurpreet Singh <lostlegend2701@gmail.com>
Closes #622 
Updated `_index.md` in kyverno CLI directory to fix command for building cli
=> [Bug] Update Makefile command for building CLI

content/en/docs/Writing policies/mutate.md
Signed-off-by: Santosh Kaluskar <dtshbl@gmail.com>
Closes #633 
Adds a note about immutable Pod fields and link to Kubernetes docs in the Mutate policies section
=> Add note about immutable Pod fields

content/en/docs/Writing policies/validate.md
Closes #617
* Adds a new section for YAML signature verification
=> add initial docs for YAML manifest validation

content/en/blog/releases/1-8-0/index.md
* Cherry picks PR #664 which will publish the blog on kyverno.io.
=> Publish Kyverno 1.8 release blog to kyverno.io (Cherry pick PR #664)

content/en/docs/Installation/_index.md
Closes https://github.com/kyverno/website/issues/668.
Just updates the documentation to be in line with the source.
=> Correct clientRateLimit defaults

content/en/resources/_index.md
=> update videos and blogs

content/en/_index.md
This PR adds minor improvements on main page.
=> chore: minor improvements on main page

content/en/docs/Writing policies/verify-images.md
Signed-off-by: pealtrufo <32867433+pealtrufo@users.noreply.github.com>
https://github.com/kyverno/kyverno/issues/4110
@chipzoller 
Added guidance to enable AWS IRSA to integrate with AWS KMS
=> IRSA to access AWS KMS

content/en/docs/Monitoring/bonus-grafana-dashboard.md
Signed-off-by: Charles-Edouard Brétéché <charles.edouard@nirmata.com>
This PR fixes image src in monitoring docs.
=> fix: image src in Monitoring docs

content/en/docs/Installation/_index.md, content/en/gatekeeper.md, layouts/partials/policies/sidebar.html
- move Helm install command up
- add guidelines for GK migration
=> update GK migration and install

config/_default/config.toml
=> new version

content/en/docs/Writing policies/policy-settings.md
Closes #757
Changed definition of background attribute for better understanding.
Before 
After
=> Changed background definition (Fixes issue #757)

config/_default/config.toml, content/en/docs/Installation/_index.md, content/en/resources/_index.md, content/en/support/nirmata/_index.md
Fixes #774 
Fixes #770 
Closes #766 
* Fixes container flag docs issues
* Adds new video playlist heading
* Adds info on Nirmata for Kyverno Open Source commercial offering
Cherry pick to 1.9 required.
=> Misc. doc updates

content/en/_index.md
This PR resolves #778
Added the trademark disclosure to improve the CLO score.
=> Add trademark disclosure 

content/en/blog/general/jmespath/index.md
Signed-off-by: Vishal Choudhary <sendtovishalchoudhary@gmail.com>
None
https://kubernetes.slack.com/archives/C032MM2CH7X/p1673274883889049?thread_ts=1673097525.979879&cid=C032MM2CH7X
Creates a blog about jmespath.
=> Blog about custom jmespath functions

content/en/docs/Kyverno CLI/_index.md
This change in the documentation is related to https://github.com/kyverno/kyverno/pull/6678 and describes the new functionality introduced in that PR.
Simple documentation change to mention the functionality introduced in https://github.com/kyverno/kyverno/pull/6678
=> Docs: Exit with WARN code if no objects satisfy a policy

content/en/docs/Writing policies/jmespath.md
Closed #796 
Added the documentation  for the new `sum()` introduced in custom JMESPath filter in kyverno.
=> [Enhancement] Add docs for sum() JMESPath filter

content/en/docs/Installation/_index.md
Closes #819 
Adding the Release Compatibility and support information from the official Nirmata docs - https://docs.nirmata.io/n4k/nirmata-enterprise-kyverno/
=> Add Enterprise Kyverno release compatibility info

content/en/resources/_index.md
Closes #811 
As the hyperlinks on the Resources Page were opening on the same page as of the website, this PR makes them redirect to their independent pages.
=> Resources Page Hyperlinks Fixed

content/en/docs/Writing policies/mutate.md
Closes #800 
* Adds a note on where not to use an add anchorr
=> add notes on add anchor

content/en/docs/Monitoring/admission-review-latency.md, content/en/docs/Monitoring/client-queries.md, content/en/docs/Monitoring/policy-changes.md, content/en/docs/Monitoring/policy-execution-latency.md, content/en/docs/Monitoring/policy-results-info.md, content/en/docs/Monitoring/policy-rule-info-total.md
This PR fixes a few metrics nits (mostly metrics names).
=> fix: metrics nits

content/en/docs/Monitoring/policy-results-info.md, content/en/docs/Monitoring/policy-rule-info-total.md
This PR fixes policy results info metric.
=> fix: policy results info metric

content/en/docs/Installation/customization.md
This PR revisits certificates docs.
Fixes #836
=> fix: certificates docs

content/en/docs/Tracing/_index.md, content/en/docs/Tracing/jaeger-walkthrough.md, content/en/docs/Tracing/tempo-walkthrough.md
Fixes https://github.com/kyverno/website/issues/858
=> update tracing docs

content/en/docs/Troubleshooting/_index.md
Fixes https://github.com/kyverno/website/issues/859
=> add troubleshooting reports section

content/en/docs/Installation/customization.md
This PR adds certificate renewal infos.
Fixes #790
=> docs: add certificate renewal infos

content/en/docs/Installation/scaling.md, content/en/docs/Writing policies/verify-images/sigstore/_index.md
Closes #875 
* Fixes a deprecated operator reference
* Adds scale testing table results
=> Add scale testing results

content/en/blog/releases/1-10-0/index.md
Updates references to just "Notary"
Cherry pick to 1.10 is required.
=> Use "Notary"

content/en/blog/general/psa-better-together/index.md
Makes some minor changes to PSA blog.
=> PSA blog updates

content/en/docs/Writing policies/autogen.md
Fixes #901. 
This PR contains a fix to a broken hyperlink found in the docs. The [relevant page](https://kyverno.io/docs/writing-policies/autogen/) points to [`policies/best-practices/disallow_default_namespace/disallow_default_namespace`](https://kyverno.io/policies/best-practices/disallow_default_namespace/disallow_default_namespace/) which was moved to [`policies/best-practices/disallow-default-namespace/disallow-default-namespace/`](https://kyverno.io/policies/best-practices/disallow-default-namespace/disallow-default-namespace/).  See #901 issue.
=> fix: update broken link to "Disallow Default Namespace" page

content/en/docs/Kyverno CLI/_index.md
Signed-off-by: Sanchita Mishra sanchita.mishra1718@gmail.com
- This PR updates the kyverno CLI binary from v1.7.2 to v1.10.0 in the manual installation. 
- It fixes the path of kyverno-cli while building the CLI from the source.
=> fix: update the path of kyverno-cli binary

CONTRIBUTING.md, README.md
@chipzoller I have removed the --recurse-submodule option from the contributing.md and readme.md file.
=> changed the readme.md and contributing.md file

content/en/blog/general/openshift-machinesets/index.md
Cherry picks PR #931 to the 1.10 release branch.
=> OpenShift blog post (Cherry pick #931)

content/en/docs/Installation/customization.md, content/en/docs/Policy Reports/_index.md, content/en/docs/Writing policies/exceptions.md
Closes #932
Closes #927
* Adds 1.10.2 specific flags
* Adds better information on Policy Exceptions and background scans
* Minor tweaks to Policy Reports page
This must be cherry picked to the release 1.10 branch.
=> Updates for 1.10.2

content/en/docs/Introduction/_index.md
Corrected Typo myredis -> newredis at https://kyverno.io/docs/introduction/
=> Typo Correction in Introduction Page

content/en/policies/best-practices/add-rolebinding/add-rolebinding.md, content/en/policies/other/s-z/update-image-tag/update-image-tag.md
=> render changes

content/en/docs/Troubleshooting/_index.md
No issue, it is something I found during the setup of Kyverno on EKS
I added a second solution to the case of  web hook timeout on EKS
=> Add solution in the EKS troubleshooting section

content/en/Community/_index.md
=> update form URL

content/en/Community/_index.md
Cherry-pick https://github.com/kyverno/website/pull/976
=> update form URL (#976)

content/en/blog/general/apply-vap-using-cli/index.md
This PR is to add a new blog for applying validating admission policies to resources using Kyverno CLI apply and test commands.
=> Add a new blog about applying VAPs to resources using Kyverno CLI

content/en/blog/general/apply-vap-using-cli/index.md, content/en/docs/Installation/customization.md, content/en/docs/Writing policies/cleanup.md, content/en/docs/Writing policies/match-exclude.md, content/en/docs/Writing policies/mutate.md, content/en/docs/Writing policies/variables.md, content/en/docs/Writing policies/verify-images/notary/_index.md, content/en/docs/Writing policies/verify-images/sigstore/_index.md, content/en/support/aws/_index.md
Supersedes #940 
Closes #971 
Closes #968 
Closes #966 
Fixes #958 
Closes #946 
Closes #934 
Closes #824 
Main changes are this adds/updates cleanup docs based on 1.11 changes.
=> 1.11 updates (part 1)

content/en/docs/Writing policies/verify-images/notary/_index.md
Adds documentation on how to verify attestations using notary
=> feat: Add manifests for attestation verification using notary

.devcontainer/tools.sh
Fixes Devcontainer to use Hugo extended.
Fixes Devcontainer to use Hugo extended.
=> Fix Devcontainer to use Hugo Extended

content/en/docs/Writing policies/jmespath.md
Use the actual function name, so the docs match the code
=> fix: Use correct function name

.devcontainer/tools.sh
Fixes a duplicate Hugo which was discovered.
=> remove duplicate hugo

content/en/Community/_index.md
Closes https://github.com/kyverno/website/issues/810.
=> Update maintainers off-boarding process

content/en/docs/Installation/customization.md, content/en/docs/Writing policies/cleanup.md, content/en/docs/Writing policies/exceptions.md
=> use v2beta1 of exceptions and cleanup policies

content/en/docs/Writing policies/jmespath.md
https://github.com/kyverno/kyverno/pull/7136
This change add the documentation for the new JMESPath function `lookup()`.
=> Add doc for JMESPath function `lookup`

content/en/blog/general/2023-security-audit/index.md
Adds the report for the 2023 Kyverno security audit and a blog post.
@JimBugwadia @realshuting 
=> Add  2023 Kyverno security audit report

content/en/docs/Monitoring/bonus-grafana-dashboard.md
- Update now dead link
- Add guide on how to enable with Helm
=> docs: update Grafana Dashboard page

content/en/docs/Installation/customization.md, content/en/docs/ValidatingAdmissionPolicy/_index.md, content/en/docs/ValidatingAdmissionPolicy/generate-validating-admission-policies.md, content/en/docs/ValidatingAdmissionPolicy/testing-validating-admission-policies.md, content/en/docs/Writing policies/generate-validating-admission-policies.md, content/en/docs/Writing policies/validate.md
Closes #956
This PR adds docs for ValidatingAdmissionPolicies.
=> add docs for validate.cel subrule

content/en/blog/general/using-cel-expressions-in-kyverno-policies/index.md
Adding a blog for the usage of CEL expressions in Kyverno policies.
=> add a blog for the usage of CEL in Kyverno policies

content/en/docs/Installation/_index.md
=> add 1.11 to the compatability matrix

content/en/docs/Kyverno CLI/_index.md
Closes #984 
Add docs for experimental fix command
=> Add docs for fix command

render/render.go
Fix render cleanup policies.
Fixes #1056
=> fix: render cleanup policies

content/en/docs/Installation/customization.md
None
Create a table for the container flags.
=> chore: create a table for the container flags

render/render.go
Remove log when rendering policies.
=> fix: remove log when rendering policies

content/en/docs/Policy Reports/_index.md, content/en/docs/Writing policies/validate.md
Add `validatingAdmissionPolicyReports` flag.
=> add validatingAdmissionPolicyReports flag

content/en/docs/Writing policies/policy-settings.md
=> typo fix: `userServerSideApply` changed to `useServerSideApply`

content/en/docs/Writing policies/mutate.md
Clarify the force reconciliation for mutate existing policies.
https://github.com/kyverno/kyverno/pull/9230
This needs to be cherry-pick to 1.11 docs.
=> Clarify mutate existing force reconciliation

content/en/docs/security/_index.md
=> Fixed a grammatical mistake

content/en/docs/Installation/customization.md
Updates the description of the `--imagePullSecrets` container flag with current information.
=> Update `imagePullSecrets` flag description

content/en/docs/Writing policies/verify-images/_index.md, content/en/docs/Writing policies/verify-images/sigstore/_index.md
NA
Adds documentation for skipImageReferences: https://github.com/kyverno/kyverno/pull/8633
=> [1.12] skipImageReferences in verify image policies

content/en/docs/Installation/customization.md, content/en/docs/Writing policies/jmespath.md
Closes #1041
* Adds the `--renewBefore` flag
* Moves a JMESPath filter doc around
=> Misc. updates

netlify.toml
Sets the Netlify `X-Frame-Options` header.
=> set x-frame-options

content/en/blog/general/kyverno-and-service-meshes/index.md
Adds a new blog entitled "Securing Services Meshes Easier with Kyverno"
[Preview link](https://deploy-preview-1143--kyverno.netlify.app/blog/2024/02/04/securing-services-meshes-easier-with-kyverno/)
Adds a new blog entitled "Securing Services Meshes Easier with Kyverno"
=> [Blog] Securing Services Meshes Easier with Kyverno

content/en/docs/Introduction/admission-controllers.md
Preview link: https://deploy-preview-1155--kyverno.netlify.app/docs/introduction/admission-controllers/
#857 
Greatly extends the Admission Controllers 101 docs.
=> Extend Admission Controllers 101

content/en/docs/Installation/customization.md
=> [Enhancement] add new flag loggingtsFormat

content/en/blog/general/assigning-node-metadata-to-pods/index.md
https://deploy-preview-1161--kyverno.netlify.app/blog/2024/02/19/assigning-node-metadata-to-pods/
Adds a new blog entitled "Assigning Node Metadata to pods"
=> [Blog] Assigning Node Metadata to pods

content/en/blog/general/generate-vaps/index.md
This PR adds a blog for generating ValidatingAdmissionPolicies from Kyverno Policies.
N/A
=> add a blog for generating VAPs

content/en/docs/Writing policies/verify-images/_index.md
=> Updated imageRegistryCredentials.secret to  imageRegistryCredentials.secrets

config/_default/hugo.toml, config/_default/params.toml
Updates some minor configs so Docsy and Hugo don't complain about deprecations.
=> Docsy fixes

content/en/docs/Writing policies/variables.md
=> [Enhancement] documenting the images variables, `reference` and `referenceWithTag`

content/en/docs/Writing policies/variables.md
small correction in the PR #1162
=> `reference` variable value corrected.

content/en/docs/Kyverno CLI/_index.md, content/en/docs/Policy Reports/validatingadmissionpolicy-reports.md, content/en/docs/Writing policies/validate.md
=> add docs for supporting bindings in the CLI and reports

content/en/docs/Writing policies/validate.md
=> fix minor bugs in the pod security exemption section

content/en/docs/Writing policies/exceptions.md
=> add docs for exception enhancements

content/en/docs/Writing policies/external-data-sources.md
Add Global Context Documentation
* https://github.com/kyverno/kyverno/pull/9601
* https://github.com/kyverno/kyverno/pull/9602
* https://github.com/kyverno/kyverno/pull/9615
* https://github.com/kyverno/kyverno/pull/9619
* https://github.com/kyverno/kyverno/pull/9640
* https://github.com/kyverno/kyverno/pull/9652
* https://github.com/kyverno/kyverno/pull/9661
* https://github.com/kyverno/kyverno/pull/9813
=> feat: add global context documentation

content/en/docs/Writing policies/external-data-sources.md
Updates GlobalContextEntry docs
=> Update global context docs

.lycheeignore, README.md, config/_default/params.toml
Adds 1.12 to the version menu but does not set as default. Updates README with modifications.
=> add 1.12 to menu

content/en/docs/Installation/_index.md
Updates compatibility matrix and minor fixes/improvements.
Cherry pick to release-1-12-0 required.
=> Compatibility updates

content/en/docs/Writing policies/external-data-sources.md
Updates a note on GlobalContextEntry.
Cherry pick to `release-1-12-0` is required.
=> Update gce note

.github/workflows/check-links.yaml
Removes the schedule from link checker.
=> remove schedule from link checker

content/en/docs/installation/customization.md
Add new container flags, see https://github.com/kyverno/kyverno/pull/10048.
=> feat: add new flags maxAuditWorkers, maxAuditCapacity

content/en/docs/kyverno-cli/assertion-trees.md, content/en/docs/kyverno-cli/usage/_index.md, content/en/docs/kyverno-cli/usage/test.md
Add docs about assertion trees in the cli.
Fixes #1197
=> feat: add docs about assertion trees in cli

content/en/resources/_index.md
NA
This PR updates the link to Grofers' Kyverno blog to Blinkit, they had a name change after their acquisition and the link redirects to Blinkit.
=> fix: update grofers link to blinkit

config/_default/params.toml, content/en/blog/releases/1-12-0/index.md
n/a
fix Release 1.12 blog date and add 1.12 versions
=> fix blog date, and versions menu

config/_default/params.toml
Update version menus in main branch
=> update versions in main

content/en/docs/Kyverno CLI/assertion-trees.md, content/en/docs/Kyverno CLI/usage/_index.md, content/en/docs/Kyverno CLI/usage/test.md
Signed-off-by: Charles-Edouard Brétéché <charles.edouard@nirmata.com>
Cherry pick #1223 to release-1-12-0
=> Cherry Pick PR 1223

content/en/docs/Installation/scaling.md
* feat: add reports controller testing results
Signed-off-by: ShutingZhao <shuting@nirmata.com>
* chore: add numbers
Signed-off-by: ShutingZhao <shuting@nirmata.com>
---------
Signed-off-by: ShutingZhao <shuting@nirmata.com>
Cherry pick #1221 to release-1-12-0
=> Cherry pick 1221

content/en/docs/installation/scaling.md
This PR updates scaling test results for the admission controller.
=> feat: update scaling test results for the admission controller

content/en/docs/Installation/scaling.md
Cherry-pick https://github.com/kyverno/website/pull/1236, https://github.com/kyverno/website/pull/1235
=> Cherry pick #1236, #1235

content/en/docs/Writing policies/verify-images/sigstore/_index.md
=> fix: remove outdated note about image pull secret

content/en/docs/Installation/methods.md
n/a
cherry-pick update replica guidance (#1265)
=> cherry-pick update replica guidance (#1265)

content/en/docs/releases/_index.md
This PR clarifies the release milestone for managing PRs.
https://github.com/kyverno/kyverno/pull/10332
=> chore: update pr management guidelines

content/en/docs/troubleshooting/_index.md
Adds a GKE docs link to troubleshooting.
=> add GKE docs link

OWNERS.md
Closes #1278
* Adds an OWNERS.md file with all current project maintainers.
=> add OWNERS.md

content/en/_index.md
=> fix typo on the home page

content/en/docs/monitoring/policy-results-info.md
=> fix: Updated doc for metric kyverno_policy_results_total to kyverno_policy_results #1325

content/en/docs/writing-policies/generate.md, content/en/policies/argo/argo-cluster-generation-from-rancher-capi/argo-cluster-generation-from-rancher-capi.md, content/en/policies/kubeops/config-syncer-secret-generation-from-rancher-capi/config-syncer-secret-generation-from-rancher-capi.md, content/en/policies/other/generate-networkpolicy-existing/generate-networkpolicy-existing.md
Closes https://github.com/kyverno/policies/issues/1162
Replaced deprecated generateExistingOnPolicyUpdate with generateExisting
=> Replaced deprecated generateExistingOnPolicyUpdate with generateExisting

content/en/docs/installation/_index.md
Closes https://github.com/kyverno/website/issues/1336.
=> feat: add 1.13 to compatibility matrix

content/en/docs/writing-policies/external-data-sources.md
https://github.com/kyverno/kyverno/pull/9883
=> feat: Add imageIndex field to imageData

content/en/docs/monitoring/_index.md
Issue - https://github.com/kyverno/kyverno/issues/9998
PR - https://github.com/kyverno/kyverno/pull/10016
This PR sends changes in https://github.com/kyverno/website/pull/1212.
=> feat: update on metrics exposure config

content/en/docs/writing-policies/generate.md, content/en/docs/writing-policies/validate.md
Closes https://github.com/kyverno/website/issues/1330.
=> feat: add generate foreach

content/en/docs/kyverno-cli/usage/test.md
[#11297
](https://github.com/kyverno/kyverno/pull/11297)
Change the docs to reflect the most up to date name for the key
=> docs: Modify patchedResource key in variables to be patchedResources

content/en/docs/installation/customization.md
=> docs: add --dumpPatches flag

content/en/docs/writing-policies/mutate.md
https://github.com/kyverno/kyverno/issues/10407
Add an example for mutation target selection using label selectors.
=> docs: Show an example for selecting targets with labels

content/en/docs/installation/customization.md, content/en/docs/writing-policies/exceptions.md
=> chore: add docs for disabling exceptions by default

content/en/docs/writing-policies/mutate.md, content/en/docs/writing-policies/validate.md
=> feat: add documentation for emit warning in mutate and validate

content/en/docs/installation/uninstallation.md
=> feat: add documentation for auto webhook deletion feature

config/_default/params.toml
=> change version to 1.13.0

config/_default/params.toml
=> update v1.13.0 menu entries

content/en/docs/installation/upgrading.md
=> fix(upgrading): v1.13 use correct Helm values

content/en/docs/introduction/quick-start.md
n/a
Fix permissions for generate policy in the quickstart
=> fix quickstart

content/en/docs/introduction/quick-start.md
=> update quickstart generate sample

content/en/docs/introduction/_index.md
=> Fix typos in the introduction page

config/_default/params.toml
=> update v1.12.0 menu entries

config/_default/params.toml
=> update v1.11.0 menu entries

content/en/docs/writing-policies/external-data-sources.md
PR hasn't been merged, reverting the change.
=> Revert "feat: Add imageIndex field to imageData"

content/en/blog/general/openshift-machinesets/index.md, content/en/policies/kasten/kasten-minimum-retention/kasten-minimum-retention.md, content/en/policies/openshift/inject-infrastructurename/inject-infrastructurename.md
=> Removes schemaValidation field

content/en/docs/monitoring/opentelemetry.md
=> docs: Corrected spell check for Deployment

content/en/docs/monitoring/kyverno-info.md
=> Adds Kyverno Info Metric page

content/en/support/infracloud/_index.md
As discussed by the InfraCloud team with @JimBugwadia
update the support section to add InfraCloud
=> add infracloud to support section

config/_default/hugo.toml, go.mod, go.sum, layouts/partials/scripts/mermaid.html
N/A
Update Hugo versions and add missing partials
=> upodate versions

.github/dependabot.yml
Add devcontainer dependabot config.
=> chore: add devcontainer dependabot config

deps/utils.go, go.mod, go.sum
=> chore: update hugo modules

.devcontainer/tools.sh, README.md
=> chore: bump hugo version

OWNERS.md, content/en/_index.md, content/en/blog/_index.md
Fix spacing between buttons in home page.
=> fix: spacing between buttons in home page

content/en/policies/kasten/kasten-minimum-retention/kasten-minimum-retention.md, content/en/policies/openshift/inject-infrastructurename/inject-infrastructurename.md, render/go.mod
=> chore: run render

.github/workflows/check-links.yaml, .github/workflows/verify-codegen.yaml, Makefile
Add codegen verification workflow.
=> chore: add codegen verification workflow

Makefile, content/en/docs/kyverno-cli/reference/kyverno.md, content/en/docs/kyverno-cli/reference/kyverno_apply.md, content/en/docs/kyverno-cli/reference/kyverno_completion.md, content/en/docs/kyverno-cli/reference/kyverno_completion_bash.md, content/en/docs/kyverno-cli/reference/kyverno_completion_fish.md, content/en/docs/kyverno-cli/reference/kyverno_completion_powershell.md, content/en/docs/kyverno-cli/reference/kyverno_completion_zsh.md, content/en/docs/kyverno-cli/reference/kyverno_create.md, content/en/docs/kyverno-cli/reference/kyverno_create_cluster-role.md, content/en/docs/kyverno-cli/reference/kyverno_create_exception.md, content/en/docs/kyverno-cli/reference/kyverno_create_metrics-config.md, content/en/docs/kyverno-cli/reference/kyverno_create_test.md, content/en/docs/kyverno-cli/reference/kyverno_create_user-info.md, content/en/docs/kyverno-cli/reference/kyverno_create_values.md, content/en/docs/kyverno-cli/reference/kyverno_docs.md, content/en/docs/kyverno-cli/reference/kyverno_jp_function.md, content/en/docs/kyverno-cli/reference/kyverno_jp_parse.md, content/en/docs/kyverno-cli/reference/kyverno_jp_query.md, content/en/docs/kyverno-cli/reference/kyverno_json.md, content/en/docs/kyverno-cli/reference/kyverno_json_scan.md, content/en/docs/kyverno-cli/reference/kyverno_migrate.md, content/en/docs/kyverno-cli/reference/kyverno_test.md, content/en/docs/kyverno-cli/reference/kyverno_version.md
Add cli reference docs to codegen verification.
=> chore: add cli reference docs to codegen verification

content/en/docs/installation/upgrading.md
This PR backports commit 9f4a024.
This fixes the broken upgrading documentation.
I feel like this should be live on the website asap since peolpe are upgrading now.
We won't have any benefit if we decide to deploy this commit on the next release.
=> Backport fix(upgrading): v1.13 use correct Helm values (#1414)

Makefile, content/en/docs/kyverno-cli/reference/kyverno.md, content/en/docs/kyverno-cli/reference/kyverno_apply.md, content/en/docs/kyverno-cli/reference/kyverno_completion.md, content/en/docs/kyverno-cli/reference/kyverno_completion_bash.md, content/en/docs/kyverno-cli/reference/kyverno_completion_fish.md, content/en/docs/kyverno-cli/reference/kyverno_completion_powershell.md, content/en/docs/kyverno-cli/reference/kyverno_completion_zsh.md, content/en/docs/kyverno-cli/reference/kyverno_create.md, content/en/docs/kyverno-cli/reference/kyverno_create_cluster-role.md, content/en/docs/kyverno-cli/reference/kyverno_create_exception.md, content/en/docs/kyverno-cli/reference/kyverno_create_metrics-config.md, content/en/docs/kyverno-cli/reference/kyverno_create_test.md, content/en/docs/kyverno-cli/reference/kyverno_create_user-info.md, content/en/docs/kyverno-cli/reference/kyverno_create_values.md, content/en/docs/kyverno-cli/reference/kyverno_docs.md, content/en/docs/kyverno-cli/reference/kyverno_jp.md, content/en/docs/kyverno-cli/reference/kyverno_jp_function.md, content/en/docs/kyverno-cli/reference/kyverno_jp_parse.md, content/en/docs/kyverno-cli/reference/kyverno_jp_query.md, content/en/docs/kyverno-cli/reference/kyverno_json.md, content/en/docs/kyverno-cli/reference/kyverno_json_scan.md, content/en/docs/kyverno-cli/reference/kyverno_migrate.md, content/en/docs/kyverno-cli/reference/kyverno_test.md, content/en/docs/kyverno-cli/reference/kyverno_version.md
=> fix: CLI reference docs links

content/en/docs/policy-types/validating-policy/_index.md
update the sample policy for kyverno CEL lib `user` and `imagedata.Get()`
https://github.com/kyverno/website/issues/1489
=> Update vpol sample

content/en/docs/policy-types/image-validating-policy/_index.md
Docs for ImageValidatingPolicy
=> update IVPOL docs

content/en/docs/policy-types/cluster-policy/external-data-sources.md
rename imageIndex to manifestList
=> Rename imageIndex to manifestList

content/en/docs/policy-types/validating-policy/_index.md
https://github.com/kyverno/kyverno/issues/12915
=> fix: correct matchConstraint for global-context example policy

content/en/docs/exceptions/_index.md, content/en/docs/policy-types/image-validating-policy/_index.md, content/en/docs/policy-types/validating-policy/_index.md
https://github.com/kyverno/website/issues/1489
Add Documentation for PolicyException Related to New Policy Types
=> add docs for policyException

layouts/partials/footer.html
This PR updates the Kyverno documentation website by adding JavaScript code generated by Reo.Dev to the footer of the website.
This script tracks and analyzes basic de-identified user interactions on the site.
Below are important FAQs about this JavaScript code. Further details can be found [here](https://docs.reo.dev/guide/how-to-embed-tracking-beacon-in-your-website-assisted-)
- The JavaScript code has been tested thoroughly to ensure that it does not introduce any vulnerabilities or risks to the website. Data sent by the JavaScript code is encrypted using the HTTPS protocol to ensure secure transmission and prevent unauthorized access
- The JavaScript code uses secure third-party libraries that have been thoroughly checked for vulnerabilities and risks
- It is designed to collect …
=> Add Reo.dev script to documentation site footer.html

content/en/support/kodekloud/_index.md
#1533 
Adding KodeKloud as a new supporter to the Kyverno website. KodeKloud offers specialized Kyverno training courses and comprehensive Kubernetes learning paths that include Kyverno policy management.
This PR:
- Creates a new supporter page for KodeKloud
- Includes links to KodeKloud's Kyverno courses and training resources
- Provides information about their enterprise training solutions
=> Add KodeKloud as Kyverno supporter

content/en/blog/releases/1-13-0/index.md, content/en/docs/kyverno-cli/reference/kyverno_apply.md, content/en/docs/kyverno-cli/reference/kyverno_test.md, content/en/docs/policy-types/image-validating-policy/_index.md, content/en/policies/other/inspect-csr/inspect-csr.md, content/en/policies/other/record-creation-details/record-creation-details.md
Closes https://github.com/kyverno/kyverno/issues/13194
changed the naming for attestations from cosign-attest ---> cosignAttestation
=> fix policy typo

content/en/docs/installation/platform-notes.md
Related ArgoCD Issue: https://github.com/argoproj/argo-cd/issues/17433
Kyverno Slack conversation: https://cloud-native.slack.com/archives/C02CEARLA3D/p1749057408140749
=> Improve Helm config.preserve guidance for ArgoCD deployments

content/en/docs/kyverno-cli/reference/kyverno_apply.md, content/en/docs/kyverno-cli/reference/kyverno_jp.md, content/en/docs/kyverno-cli/reference/kyverno_jp_function.md, content/en/docs/kyverno-cli/reference/kyverno_jp_query.md, content/en/docs/kyverno-cli/reference/kyverno_test.md, content/en/docs/kyverno-cli/usage/apply.md, content/en/docs/kyverno-cli/usage/test.md
=> add docs for ValidatingPolicies in the CLI

content/en/docs/policy-types/validating-policy/_index.md
https://github.com/kyverno/website/issues/1574
Rename the table entry image() → parseImageReference()
Update all example snippets that call image(...) to use parseImageReference(...)
=> refactored library

content/en/_index.md, content/en/docs/policy-types/_index.md, content/en/docs/policy-types/cel-libraries/_index.md, content/en/docs/policy-types/cleanup-policy/_index.md, content/en/docs/policy-types/cluster-policy/_index.md, content/en/docs/policy-types/deleting-policy/_index.md, content/en/docs/policy-types/generating-policy/_index.md, content/en/docs/policy-types/image-validating-policy/_index.md, content/en/docs/policy-types/mutating-policy/_index.md, content/en/docs/policy-types/validating-policy/_index.md, layouts/shortcodes/feature-state.html
n/a
* Re-organized and update `Policy Types` page
* Update home page
=> update policy types and home page

config/_default/params.toml
=> fix version links

config/_default/params.toml
n/a
Remove unsupported versions
=> Fix 1.15 version

content/en/docs/monitoring/kyverno-info.md
Replace Kyvero by Kyverno
Typo in Kyverno documentation
Replace Kyvero by Kyverno
=> [Doc] Update kyverno-info.md to correct a typo
