assets/scss/main.scss
content/en/resources/_index.md
layouts/shortcodes/videos.html
layouts/shortcodes/youtube.html

Switch from using inline HTML to a Hugo [shortcode](https://gohugo.io/content-management/shortcodes/) that references the same YouTube videos.

Use YouTube shortcode for videos

---

Makefile
scripts/hash-files.sh

The name _kubernetes-hugo_ came from the Kubernetes [_k/website_](https://github.com/kubernetes/website/pulls) repo where this `Makefile` originated. Switch to _kyverno-hugo_.
Also, bring over a missing `scripts/hash-files.sh` from that repo.

Fix image name for local previewing

---

Makefile

As this deprecation happened before the code was live, it's fair to assume  that people aren't using the deprecated targets. Remove them.

Remove already-deprecated local actions

---

content/en/docs/Installation/_index.md
content/en/docs/Kyverno CLI/_index.md
content/en/docs/Policy Violations/_index.md
content/en/docs/Writing policies/match-exclude.md
content/en/docs/Writing policies/mutate.md
content/en/docs/Writing policies/variables.md

Taking a steer from the Kubernetes documentation [style guide](https://kubernetes.io/docs/contribute/style/style-guide/), fix Markdown for code blocks and monospaced inlines.
- mark YAML as YAML
- don't include the prompt in code highlighted as shell
- use CommonMark preformatted blocks (<tt>\`\`\`</tt> delimited)
Plus a few wording tweaks that I could separate out but will only create merge conflicts if I do.

Tidy monospaced blocks and inlines

---

content/en/docs/Introduction/_index.md

When we create the policy in the quick start example, the character ` makes the shell execute and an error is reported. As a consequence, the validation message shows incorrectly.
```
kubectl create -f- << EOF
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
name: require-labels
spec:
validationFailureAction: enforce
rules:
- name: check-for-labels
match:
resources:
kinds:
- Pod
validate:
message: "label `app.kubernetes.io/name` is required"
pattern:
metadata:
labels:
app.kubernetes.io/name: "?*"
EOF
zsh: no such file or directory: app.kubernetes.io/name
clusterpolicy.kyverno.io/require-labels created
```
```
kubectl create deployment nginx --image=nginx
Error from server: admission webhook "validate.kyverno.svc" denied the request:
resource Deployment/default/nginx was blocked due …
```

fix shell execution in example

---

content/en/docs/Writing policies/mutate.md

The yes is treated as a boolean and results in an error.

Quote yes to treat it as a string

---

content/en/docs/Writing policies/preconditions.md

Signed-off-by: Arsh Sharma <arshsharma461@gmail.com>
Reasoning:
If **any** of the strings part of the key is **not** in the value set then it is reason enough for NotIn to say that it is not a subset and return true.

docs(preconditions): fixed definition of NotIn for sets

---

content/en/docs/Writing policies/preconditions.md
content/en/docs/Writing policies/validate.md

Adds documentation for the `any`/`all` statement blocks referenced in https://github.com/kyverno/kyverno/issues/1765 (see referenced PR and parent issue) which adds functionality to `validate.deny.conditions` and `preconditions` objects. The ultimate objective would be to link to the same section under the preconditions portion of these docs when this capability is expanded to other Kyverno sections as outlined in https://github.com/kyverno/kyverno/issues/1485 (such as `pattern`, `anyPattern`, `matchExpressions`, and `matchLabels`)
Closes #104

Add any/all documentation

---

content/en/docs/Writing policies/verify-images.md
content/en/policies/other/verify_image.md

The actual example images are "test-verify-image", but the docs and
policy use "test-image-verify".
Signed-off-by: Dan Lorenc <dlorenc@google.com>

Fix typo in cosign tutorial.

---

content/en/docs/Installation/_index.md

This documents changes from https://github.com/kyverno/kyverno/pull/2218.  To keep things consistent I put all Helm arguments after the positional arguments. Some places had `--namespace` flag before positional arguments, and some places had it after, so I moved them all to after.

Document Kyverno CRDs Helm chart

---

assets/scss/main.scss

As of now, the user has to scroll horizontally on mobile screens to view half of the videos which affects the UX of the website.
With this PR, all the videos will horizontally fit in the screen (if not enough to accommodate 2 videos horizontally, it would push the other one down)
The video thumbnails on the [resources page](https://kyverno.io/resources/) have been made responsive.
- Wrapped them inside a `flex-wrap`
- Margin set to 1 rem to adjust for all the devices
| Before | ![image](https://user-images.githubusercontent.com/55556994/130263246-26b9de1c-ae15-4719-955b-33f670bbbf2c.png) |
| -------- | --------- |
| After | ![image](https://user-images.githubusercontent.com/55556994/130263328-be6e883f-d33a-4fcb-a365-656720adf966.png) |
| Device | Before | After |
| ------- | ------- | …

Video thumbnails made responsive

---

assets/scss/_styles_project.scss
layouts/partials/navbar-version-selector.html
layouts/partials/navbar.html

Fixes #238 
- For Desktop, it is as it is before
- For mobile screens, a drop-down menu appears when you click on the button on the right margin that shows the entire nav-bar including a further drop-down for the versions
Before | After
-------- | ---------
| Situation |  Screen
-------- | ---------
Idle | <img src="https://user-images.githubusercontent.com/55556994/129589376-0fc90833-6c1b-460f-b858-7e5957962f5f.png" height=300>
Clicking on the expand button |  <img src="https://user-images.githubusercontent.com/55556994/129588496-8f771835-1f27-45ad-a1e1-bad7e0b1508d.png" height=300>
Drop-down for versions | <img src="https://user-images.githubusercontent.com/55556994/129589459-c306636e-5db8-40ca-a403-f2d3936911c0.png" height=300>

Drop down nav bar for mobile

---

content/en/docs/Installation/_index.md

Signed-off-by: Trey Dockendorf <tdockendorf@osc.edu>
In response to https://github.com/kyverno/kyverno/pull/2357
For the upgrade steps, I opted for "simplest" approach where do full uninstall/re-install.  There are less simple ways to do upgrade documented in https://github.com/kyverno/kyverno/pull/2357 but wasn't sure if was good to document those steps.

[1.5.0] Update install/update/uninstall steps for Helm chart changes

---

content/en/docs/Installation/_index.md
content/en/docs/Introduction/_index.md

Currently installing kyverno from the release manifest using the steps from docs gives this error:
```
error: unable to read URL "https://raw.githubusercontent.com/kyverno/kyverno/main/definitions/release/install.yaml", server reported 404 Not Found, status code=404
```
This is because definitions folder doesn't exist anymore and the install.yaml lies in config/release, this PR updates that
Signed-off-by: Mritunjay Sharma <mritunjaysharma394@gmail.com>

updates install kyverno steps from release manifest

---

content/en/docs/Installation/_index.md

Signed-off-by: ShubhamPalriwala <spalriwalau@gmail.com>
For the current release, we are unable to download the SBOM  hence we should remove it from the current release docs. It will be ready once v1.5.2 is released hence it is present as it is in our `main` branch.
In case of signing, as PR https://github.com/kyverno/kyverno/pull/2536 is added as 1.5.2 milestone, the current docs in main are misleading hence for an immediate fix, we can update it as to how it works in for v1.5.1

update: signing and sbom as per release 1.5.1

---

content/en/docs/Monitoring Kyverno With Prometheus Metrics/policy-results-info.md

Fixing example query to get number for failed requests in 24 hours in default namespace.

Fixing query for failed rules

---

content/en/docs/security/_index.md

The hyperlinks in headers caused unexpected behaviors when shown in the RHS index. Clicking on the index entry would redirect to the link, instead of the section. 
Also moved the networking section up.

remove links from headers in security section

---

config/_default/config.toml
config/_default/params.toml

Config updates. Not sure why https://release-1-6-0.kyverno.io/ isn't working at this point. I thought it should after I created the subdomain. But these config file changes are needed anyhow.

Release 1 6 0

---

content/en/docs/Writing policies/external-data-sources.md

Brought up in Slack: https://kubernetes.slack.com/archives/CLGR9BJU9/p1650304196171389
Provide link to how to define private registries for imageData policies.

Document imageData policies can also use private registries

---

content/en/docs/Writing policies/match-exclude.md

Signed-off-by: Tathagata Paul <tathagatapaul7@gmail.com>
Fix documentation for "match-exclude" where a hyphen (-) was missing

Fix missing hyphen (-) in doc

---

content/en/docs/Writing policies/jmespath.md

Closes #529 
Closes #530 
* Adds documentation on new custom JMESPath filters `items()` and `object_from_list()`
Cherry pick to 1.7.0 branch is needed.

[1.7.0] Add docs on `items()` and `object_from_list()` JMESPath filters

---

content/en/docs/Writing policies/mutate.md

Signed-off-by: Rafael Ceccone <rafael@ceccone.net>
Fix the anchor link for mutate existing resources.

fix link for mutate existing resources

---

render/render.go

Signed-off-by: weru <fromweru@gmail.com>
Closes #547 
@chipzoller 
We were querying the entire policy contents to determine what the policy type is. This way, if the name of a policy type e.g `generate` was found somewhere before the spec declaration, that policy would be assigned that type.
Obviously, it's more fool-proof to query for the type after the spec declaration i.e  after👇🏼 
```yaml
...
spec: 
...
```
I have render the policies locally and the issue seems to be fixed with no regressions

extract policy-type after spec declaration

---

content/en/docs/Installation/_index.md
content/en/docs/Writing policies/validate.md

Closes #604 
Closes #620 
* Adds docs on the new podSecurity sub-rule type in 1.8
* Adds deprecation note for `splitPolicyReports` flag
* Adds new container flags
* Remove old annotation notes

add podSecurity docs for 1.8

---

content/en/docs/Tracing/jaeger-walkthrough.md
content/en/docs/Tracing/tempo-walkthrough.md

Signed-off-by: Charles-Edouard Brétéché <charles.edouard@nirmata.com>
This PR removes `--devel` from tracing tutorials.
Closes #746

fix: remove --devel from tracing tutorials

---

content/en/docs/Writing policies/variables.md

fix: typo in writing policies / variables

---

content/en/docs/Installation/_index.md

Coming from [a Slack question](https://kubernetes.slack.com/archives/CLGR9BJU9/p1679589356578679)
Adds a clarification of the default behavior if the `--exceptionNamespace` flag is unset.

Clarify default PolicyException namespace behavior

---

content/en/_index.md

Closes #791 
As the hyperlinks on the homepage were opening in the same page as of the website, this PR makes them redirect to their independent pages.

Homepage Hyperlinks Fixed

---

content/en/docs/Troubleshooting/_index.md

Closes #788 
Based on our findings in https://github.com/kyverno/kyverno/issues/6539 we want to add a new Troubleshooting section about aks managed clusters and the webhook endless loop.

Add Troubleshooting section for high resource usage on AKS 

---

content/en/docs/Monitoring/policy-rule-info-total.md

This PR fixes policy rule info total metric:
- one `|` was missing in the last row of the labels table

fix: policy rule info total

---

content/en/Community/_index.md

Update Contributors section:
- collapse role descriptions and details
- add a note for contributors to create a PR to add themselves

collapse roles and add self-service note for Contributors

---

content/en/Community/_index.md

Cherry-pick: https://github.com/kyverno/website/commit/37f6c83f2dbeeebb67d1f6f9a0d4889cd7625267
* collapse roles and add self-service note for Contributors
* fix typos
* flip columns and revert contributor responsibilities
---------

cherry-pick: collapse roles and add self-service note for Contributors (#883)

---

content/en/docs/Writing policies/policy-settings.md

Fixes #896. 
This PR contains a fix to a broken hyperlink found in the docs. The [relevant page](https://kyverno.io/docs/writing-policies/policy-settings/) points to [`docs/writing-policies/background/`](https://kyverno.io/docs/writing-policies/background/) which was moved to [`docs/policy-reports/background/`](https://kyverno.io/docs/policy-reports/background/).  See #896 issue.

fix: update broken link to background scans page

---

content/en/docs/Writing policies/jmespath.md

fixed   #972 
I have rectifed the typo- "The page has a sentence:
"Whatever the value of the `namespace` key is will be inserted where the expression is written."
Where a word 'it' is missing"
to 
"Whatever the value of the `namespace` key is, it will be inserted where the expression is written."

fixed the typo in JMSEPath in issue#972 

---

content/en/docs/Kyverno Policies/_index.md

This is just a result of a probable diagnosis on my part. :)
Just moving a dot to the correct side of the parentheses.

Move dot in Kyverno Policies documentation page

---

content/en/docs/Monitoring/_index.md

https://github.com/kyverno/kyverno/issues/8401
https://github.com/kyverno/kyverno/pull/8569
This changes evolves the metrics related configuration done via the `kyverno-metrics` ConfigMap, exposing two new fields as following:
- `metricsExposure`: this is a map of a struct allowing each metric to be disabled, filtered labels or changed the bucket boundaries.
- `bucketBoundaries`: this configures the default bucket boundaries for all histograms.
It's worth mentioning this change does not change the default metrics configuration currently in use by Kyverno, meaning that all metrics, labels and bucket dimensions currently in use are preserved by default.

fix: allow dropping metrics, labels and configuring histogram bucket boundaries to avoid high cardinality

---

content/en/docs/Writing policies/verify-images/_index.md

Closes: #985 
Adds docs for `imageRegistryCredentials`  in `verifyImage` policies that can be used to configure registry credentials per policy.

feat: add documentation for imageRegistryCredentials

---

content/en/docs/Monitoring/bonus-grafana-dashboard.md

The current Grafana Dashboard JSON URL appears to point to an old repo, I found the equivalent in the new repo and updated the docs accordingly. This appears to be the only reference to this URL in the docs and I verified with `hugo server` and running the new command on my terminal.

fix: Update Grafana Dashboard JSON URL

---

content/en/policies/best-practices/disallow-cri-sock-mount/disallow-cri-sock-mount.md
content/en/policies/cleanup/cleanup-empty-replicasets/cleanup-empty-replicasets.md
content/en/policies/other/memory-requests-equal-limits/memory-requests-equal-limits.md
content/en/policies/other/require-emptydir-requests-limits/require-emptydir-requests-limits.md
content/en/policies/pod-security-cel/baseline/disallow-host-ports-range/disallow-host-ports-range.md
content/en/policies/pod-security-cel/baseline/disallow-privileged-containers/disallow-privileged-containers.md
content/en/policies/pod-security-cel/baseline/disallow-proc-mount/disallow-proc-mount.md
content/en/policies/pod-security-cel/baseline/disallow-selinux/disallow-selinux.md
content/en/policies/pod-security-cel/baseline/restrict-seccomp/restrict-seccomp.md
content/en/policies/pod-security-cel/baseline/restrict-sysctls/restrict-sysctls.md
content/en/policies/pod-security/baseline/disallow-host-ports-range/disallow-host-ports-range.md

Renders policies. The CleanUp filter does not return the one rendered ClusterCleanupPolicy. Need to fix.
Cherry pick required to release-1.11

Render policies

---

content/en/docs/Installation/customization.md

doc(flag): add maxAPICallResponseLength flag

---

content/en/blog/general/introducing-reports-server/index.md

N/A
This pr adds `apiserver_storage_objects` metric to reports-server blog which shows the number of resources stored in etcd.

feat: add apiserver storage object metric to reports-server blog

---

content/en/docs/installation/methods.md

The current example doesn't render properly using helm `version.BuildInfo{Version:"v3.14.3", GitCommit:"f03cc04caaa8f6d7c3e67cf918929150cf6f3f12", GitTreeState:"clean", GoVersion:"go1.22.1"}
`

Helm values.yaml file example doesn't work for high availability

---

content/en/policies/best-practices/require-pod-requests-limits/require-pod-requests-limits.md

Signed-off-by: nikhilmaheshwari24 [nikhil.m2498@gmail.com](mailto:nikhil.m2498@gmail.com)
https://github.com/kyverno/policies/issues/951
This PR updates the existing Kyverno policy to validate CPU and memory resource requests and limits for both containers and initContainers within Pods. This enhancement ensures comprehensive resource management across all container types in a Kubernetes cluster.

Enhance Resource Constraints Validation Policy to Include InitContainers

---

content/en/docs/writing-policies/verify-images/sigstore/_index.md

[#10645](https://github.com/kyverno/kyverno/issues/10645#issuecomment-2265627588)
Fix rekor.pubkey and ctlog.pubkey like [schema of a CRD](https://github.com/kyverno/kyverno/blob/main/docs/user/crd/kyverno.v1.html#L2231). In my case, this is important when deploying verify image policy through ArgoCD.

Fix rekor.pubkey & ctlog.pubkey

---

layouts/partials/footer.html

@JimBugwadia
This PR updates the Kyverno documentation website by adding a pixel to the footer of the website. The pixel does not impact site speed times, does not contain cookies or JavaScript, and is purely an HTML image that collects basic de-identified download and adoption metrics.
This change was suggested in direct discussions with Kyverno folks. 
Scarf purges PII, complies with the GDPR, and is approved for usage by the CNCF. Kyverno users can easily opt out of analytics in various ways documented [here](https://docs.scarf.sh/gateway/#do-not-track). 

Add Scarf documentation pixel to site footer

---

render/render.go

Fixes #929 
The bug was due to the code not recursively searching the directory for `.md` files. We have modified the code to search directories and sub-directories.

bugfix: `Render` to cleanup all the directories

---

content/en/docs/installation/methods.md

Minor update the installation part for better guidance, especially for beginners.

minor update installation methods

---

content/en/policies/other/mitigate-log4shell/mitigate-log4shell.md

#1340 
Security link for log4j is updated. 
Old: https://logging.apache.org/log4j/2.x/security.html
New: https://logging.apache.org/security.html

fix: update log4j security link

---

content/en/docs/installation/customization.md

fixing inconsistent documentation on certificates renewal time before expiration.
https://github.com/kyverno/kyverno/blob/8fec1ad76431a084cc62fedefaaa24a4a96a8953/cmd/kyverno/main.go#L298
```go
flagset.DurationVar(&renewBefore, "renewBefore", 15*24*time.Hour, "The certificate renewal time before expiration")
```

update certificates renewal time before expiration

---

content/en/blog/general/introducing-reports-server/index.md
content/en/blog/general/slsa-3/index.md
content/en/docs/security/_index.md
content/en/docs/writing-policies/verify-images/sigstore/_index.md

fix: update broken links

---

content/en/docs/kyverno-cli/usage/apply.md
content/en/docs/kyverno-cli/usage/test.md
content/en/docs/policy-reports/validatingadmissionpolicy-reports.md
content/en/docs/writing-policies/validate.md

add docs for VAPs

---

content/en/docs/writing-policies/cleanup.md
content/en/docs/writing-policies/exceptions.md
content/en/docs/writing-policies/verify-images/_index.md

feat: remove beta warning from image verify, exceptions and cleanup policy docs

---

README.md

When you first setup a codespace in github to run the website it is defaulted to the hugo version that comes with codespaces. But website requires hugo extended version to be installed.
Documentation added to manually install hugo extended version in the github codespaces.

doc: update hugo installation for github codespaces users

---

content/en/blog/general/why-chainsaw-is-unique/index.md

Fixes #1368 
Updated the function from `len` to `length`.

chore: updated JMESPath function

---

netlify.toml

Close #1367
Sets CORS header for RSS feed `/blog/index.xml` to allow to all.
This will allow using the feed in a Grafana dashboard news panel.

Enable CORS for RSS feed

---

content/en/_index.md
layouts/partials/footer.html

n/a
- Update banner title & test
- Update footer

fix footer; update banner

---

.github/workflows/check-links.yaml
config/lychee.toml
content/en/docs/writing-policies/variables.md
lychee.toml

Fixes https://github.com/kyverno/website/issues/1364
Docs for shallow substitution.

add shallow substitution docs

---

content/en/docs/writing-policies/mutate.md
content/en/docs/writing-policies/policy-settings.md
content/en/docs/writing-policies/variables.md

Related to https://github.com/kyverno/website/issues/1335

docs: add warning for the mutateExistingOnPolicyUpdate deprecated field

---

content/en/docs/writing-policies/generate.md
content/en/docs/writing-policies/policy-settings.md
content/en/policies/argo/argo-cluster-generation-from-rancher-capi/argo-cluster-generation-from-rancher-capi.md
content/en/policies/kubeops/config-syncer-secret-generation-from-rancher-capi/config-syncer-secret-generation-from-rancher-capi.md
content/en/policies/other/generate-networkpolicy-existing/generate-networkpolicy-existing.md

Related to https://github.com/kyverno/website/issues/1335

docs: add warning for the generateExisting deprecated field

---

content/en/docs/installation/customization.md
content/en/docs/policy-reports/_index.md

https://github.com/kyverno/kyverno/pull/11376
Adds documentation for new reporting configuration changes

feat: add documentation for new reporting configuration changes

---

content/en/docs/writing-policies/verify-images/sigstore/_index.md

Related to: https://github.com/kyverno/kyverno/pull/10815
Add documentation for  2 new field in keyless called `subjectRegExp` and `issuerRegExp` to allow regular expressions in cosign keyless verification

feat(docs): regexp support in cosign keyless verification

---

content/en/docs/kyverno-cli/usage/apply.md
content/en/docs/kyverno-cli/usage/test.md
content/en/docs/writing-policies/cleanup.md
content/en/docs/writing-policies/exceptions.md

Related to https://github.com/kyverno/website/issues/1335

docs: use v2 for cleanup policies and exceptions

---

content/en/docs/writing-policies/validate.md

#1316 
Validation Documentation for assert subrule

[Enhancement] assert subrule documentation

---

content/en/docs/policy-reports/_index.md

fix: add warning to set permission in reports controller

---

content/en/docs/kyverno-cli/usage/apply.md
content/en/docs/writing-policies/external-data-sources.md

Add a section about hot to use Global Context Entries in the CLI.

doc(gctx): cli variable injection

---

content/en/docs/writing-policies/mutate.md

https://github.com/kyverno/kyverno/issues/5164
Drop mention of the `last-applied-patches` annotation
Also, mention that by default Kyverno does not emit PolicyApplied events

fix(mutate): drop mention of the last-applied-patches annotation

---

content/en/blog/general/introducing-kyverno-envoy-plugin/index.md
content/en/docs/writing-policies/mutate.md

#1448 
This PR addresses two issues in the documentation
- Fixes a broken link to the GitHub repository by updating it with the correct URL.
- Corrects the ArgoCD header name in the URL to ensure it accurately points to the right section.
Files Modified:
content/en/blog/general/introducing-kyverno-envoy-plugin/index.md
content/en/docs/writing-policies/mutate.md

Fix broken links and update ArgoCD header

---

content/en/docs/CRDs/_index.md

This PR fixes the link for kubernetes extension, which currently points to [https://code.visualstudio.com/docs/azure/kubernetes] instead of https://code.visualstudio.com/docs/azure/kubernetes#_install-the-kubernetes-extension
Changes made to : content/en/docs/CRDs/index.md

Fixed link for kubernetes extension installation

---

content/en/docs/kyverno-cli/assertion-trees.md

This PR addresses issue in the documentation about Working with assertion trees.
Currently the link in docs point to wrong documentation (policies), which actually should have been "Assertion trees in kyverno-json"
File modified:
content/en/docs/kyverno-cli/assertion-trees.md
Checklist
I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
I have inspected the website preview for accuracy.
I have signed off my issue.

Fix: Fixed the link for assertion tress in documentation

---

content/en/docs/policy-types/cluster-policy/policy-rules/_index.md

This PR fixes the dead link behind 'Applying Policies' in the policy rules documentation. The link was incorrectly using `/doc/applying-policies/_index.md` instead of `/docs/applying-policies/`, which was causing a 404 error. This change ensures users can properly navigate to the applying policies documentation.

Fix applying policies link

---

content/en/docs/policy-types/cluster-policy/variables.md

Add to variables doc:
In Kyverno, for a plain JMESPath variable, no double curly brackets are needed but for nested variables you need to use the double braces syntax.
For example:
```
- name: mountpath
variable:
jmesPath: request.object.metadata.annotations.optional || '/custom/string/{{request.object.metadata.annotations.mandatory"}}'
```
Here, no double curly brackets are needed in `request.object.metadata.annotations.optional` but for nested variables like `/custom/string/{{request.object.metadata.annotations.mandatory"}}`, you need wrap variable with `{{}}`.
@realshuting @vishal-chdhry Please review this.

#1388 Update variables to show when to wrap variables in double braces
